name: Update Vercel Environment Variables

on:
  push:
    branches:
      - main

jobs:
  update-vercel-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Vercel Environment Variables
        env:
          VERCEL_TOKEN: ndvdUdQr6LQNx4aSuSs0iTm1
          VERCEL_PROJECT_ID: prj_dKW3xqAK2X1c0La0oECdCaM6jERp
        run: |
          # Define your environment variables
       
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version extracted: ${{ secrets.VERCEL_TOKEN }}" 
          # Update environment variables in Vercel
          curl -X PATCH "https://api.vercel.com/v9/projects/prj_dKW3xqAK2X1c0La0oECdCaM6jERp/env/y9JTcVZONBPRLi38" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_PROJECT_ID }}" \
          -H "Content-Type: application/json" \
          -d '{"value":"4.3.0"}'

