name: Update Vercel Environment Variables

on:
  push:
    branches:
      - main

jobs:
  update-vercel-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Vercel Environment Variables
        env:
          VERCEL_TOKEN: ndvdUdQr6LQNx4aSuSs0iTm1
          VERCEL_PROJECT_ID: prj_dKW3xqAK2X1c0La0oECdCaM6jERp
        run: |
          # Define your environment variables
          ENV_VARIABLES='[
            {"key":"TEST","value":"new_value1"},
            
          ]'

          # Update environment variables in Vercel
          curl -X PATCH "https://api.vercel.com/v8/projects/prj_dKW3xqAK2X1c0La0oECdCaM6jERp/env" \
          -H "Authorization: Bearer ndvdUdQr6LQNx4aSuSs0iTm1" \
          -H "Content-Type: application/json" \
          -d "$ENV_VARIABLES"

